# Generated by Django 5.1.3 on 2024-11-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0005_rename_lote_productos_marca_productos_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.IntegerField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
