# Generated by Django 5.1.3 on 2024-11-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos_app', '0006_alter_productos_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
