# Generated by Django 5.1.3 on 2024-11-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('usuario', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
            ],
        ),
    ]
