# Generated by Django 5.1.3 on 2024-11-29 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='usuario',
            new_name='nombre',
        ),
    ]
