# Generated by Django 5.1.3 on 2024-11-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente_app', '0002_rename_direrccion_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='metodo_de_pago',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo_cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='No Apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='No apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateField(default='2024-01-01', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
