# Generated by Django 5.1.3 on 2024-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores_app', '0003_proveedor_fecha_ultimo_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='id_sucursal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
