# Generated by Django 5.1.3 on 2024-11-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.AddField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(default='Desconocido', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empleado',
            name='salario',
            field=models.FloatField(default=0.0, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
