# Generated by Django 5.1.3 on 2024-11-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados_app', '0002_rename_apellido_empleado_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id_empleado',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
