# Generated by Django 5.1.3 on 2024-11-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal_app', '0002_alter_envio_estado_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Envio',
        ),
    ]
